# Generated by Django 2.1.7 on 2019-03-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190310_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
