# Generated by Django 2.1.7 on 2019-03-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
